### ISSUE TITLE
What size of tubing should be used?

### ISSUE THREAD

**Issue by LukeTowers** [gcormier/esphome-pressure#3]
What size of tubing is needed and do you have any recommendations for where to source it from?

**Comment by gcormier** [comment]
The biggest part of the barb is 3mm in diameter. So if you are using a stiffer tuber, it should be close to that for the ID. If you are using a soft material, it can probably be a bit smaller.

I bought mine from homedepot - I would bring the device to your local store to see what fits best, I would hate to recommend something that doesn't fit :) I no longer have the packing for mine. it is a clear, fairly stiff, tube. Next time I would probably splurge on something softer like silicone perhaps, but it doesn't matter in the end since it is static pressure so there is no airflow.

**Comment by kramttocs** [comment]
I ordered Pure Silicone Tubing 1/16 ID x 1/8 OD and it fit well.

**Comment by gcormier** [comment]
Now covered in the readme - https://github.com/gcormier/esphome-pressure?tab=readme-ov-file#hosetubing

**Comment by kramttocs** [comment]
Actually, I retract my 1/16 suggestion. It does work but it is tough to connect to the common 1/8 fittings. 
Ordered this and it works much better:

Quickun Pure Silicone Tubing, 2mm ID x 4mm OD High Temp Food Grade Tube Pure Silicone Hose Tube for Home Brewing, Beer Line, Kegerator, Wine Making, Aquaponics, Air Hose by Proper Pour (16.4 Ft)

**Comment by gcormier** [comment]
thx have modified readme
